apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-demo-app"
  annotations:
    github.com/project-slug: twirlyz/my-demo-app
    github.com/user: 'twirlyz'
spec:
  type: service
  owner: user:twirlyz
  lifecycle: experimental
  dependsOn: 
    - "resource:my-demo-app-ec2"
